### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Apollo3zehn** [Apollo3zehn/ImcFamosFile#1]
- [x] Distribute FamosFileField level XAxisScaling to underlying FamosFileComponents after deserialization. Otherwise XAxisScaling property is null.
- [ ] Implement Ca key once a sample file is available.
- [x] Find definitions for this group of properties and make them public then:
```
private int Reduction { get; set; }
private int IsMultiEvents { get; set; }
private int SortBuffers { get; set; }
```
- [x] Implement ```FamosFileValidCR2Type```
- [ ] Validate ```FamosFileDataType.ImcDevicesTransitionalRecording```
- [ ] Validate ```FamosFileDataType.AsciiTimeStamp```
- [x] Validate ```FamosFilePropertyType.TimeStampInDMFormat```
- [ ] Validate ```FamosFilePropertyType.Enumeration```
- [ ] Find out if events really have own indices. This is unclear from documentation.
- [ ] Fix wrong event definition (|CV)
- [ ] Reading buffer info user data may fail because lengths is unknown.
